// otus-vue/src/App.vue
<template>
  <div id="app">
    <div id="nav">
      <router-link to="/">Home</router-link> |
      <router-link to="/settings">Settings</router-link> |
      <router-link to="/game">Game</router-link>
    </div>
    <router-view />
  </div>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#nav {
  margin: 30px;
}

#nav a {
  font-weight: bold;
  color: #2c3e50;
}

#nav a.router-link-exact-active {
  color: #42b983;
}
</style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  styles: [
    `
      .nav {
        clear: both;
      }
      a {
        float: left;
      }
      .active a {
        color: red;
      }
    `,
  ],
  template: `<div class="page-header">
    <h1 class="toolbar__title">
      Добро пожаловать в приложение для запоминания иностранных слов
      <ul class="nav">
        <li
          routerLinkActive="active"
          [routerLinkActiveOptions]="{ exact: true }"
        >
          <a routerLink="">Главная</a>
        </li>
        <li routerLinkActive="active">
          <a routerLink="/game">Игра</a>
        </li>
        <li routerLinkActive="active">
          <a routerLink="/settings">Настройки</a>
        </li>
      </ul>
      <router-outlet></router-outlet>
    </h1>
  </div>`,
})
export class AppComponent {}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
</style>

<!-- Toolbar -->
<div class="toolbar" role="banner">
</div>

<router-outlet></router-outlet>
